config/routes.rb
Rails.application.routes.draw do
  get '/wikis/private_index' => 'wikis#private_index'

  resources :wikis do
    resources :collaborators, only: [:index, :destroy]
    match '/collaborators/:id' => 'collaborators#create', :via => :post

  end

  resources :charges, only: [:new, :create]

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  validates :wiki_id, presence: true
  validates :user_id, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :roles
  has_many :wikis, through: :collaborators
  has_many :collaborators

  validates :name, length: { maximum: 20 }

  before_create :set_default_role
  after_initialize :downgrade
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def admin?
    role == 'admin'
  end

  def admin_premium?
    role == 'premium' || role == 'admin'
  end

  def standard!
    update(role: 'standard')
  end

  def premium!
    update(role: 'premium')
  end

  def admin!
    update(role: 'admin')
  end

  def downgrade
    if role == 'standard'
      Wiki.where(user: self, private: true).update_all(private: false)
    end
  end

  private

  def set_default_role
    self.role ||= 'standard'
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators, dependent: :destroy

  validates :title, length: { maximum: 150 }, presence: true
  validates :body, length: { maximum: 750 }, presence: true
  validates :user, presence: true

  default_scope { order('title ASC') }

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    # Add my attributes added to the devise User class
    devise_parameter_sanitizer.for(:sign_up) << :name << :access
    devise_parameter_sanitizer.for(:account_update) << :name << :access
    devise_parameter_sanitizer.for(:account_update) << :role << :access
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
    if current_user.standard?
      charge = Stripe::Charge.create(
        customer: customer.id,
        amount: 15_00,
        description: "Premium Wiki Membership - #{current_user.email}",
        currency: 'usd'
      )
      current_user.update_attributes!(role: 'premium')
      flash[:notice] = "Thanks for upgrading, #{current_user.email}!"
      redirect_to wikis_path
    end

  rescue Stripe::CardError => e
    flash.now[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    if current_user.standard?
      @stripe_btn_data = {
        key: Rails.configuration.stripe[:publishable_key].to_s,
        description: "Premium Wiki Membership - #{current_user.name}",
        amount: 15_00
      }
    end
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators = nil || User.where.not(role: 'standard', id: current_user.id)
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find_by(user_id: params[:id])

    if @collaborator.delete
      flash[:notice] = "Collaborator removed"
      redirect_to wiki_collaborators_path(@wiki)
    else
      flash[:notice] = "There was an error removing the Collaborator."
      redirect_to edit_wiki_path(@wiki)
    end
  end

  def create
    @user = User.find(params[:id])
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new(user: @user, wiki: @wiki)

    if @collaborator.save
      flash[:notice] = "Collaborators have been saved."
      redirect_to wiki_collaborators_path(@wiki)
    else
      flash[:error] = "An error occured we were unable to save the collaborators"
      redirect_to edit_wiki_path(@wiki)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_policy_scoped, only: [:private_index]

  def index
    @wikis = Wiki.where(private: false)
    authorize @wikis
  end

  def private_index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.create(create_params)
    @wiki.user = current_user
    authorize@wiki

    if @wiki.save
      flash[:notice] = 'Wiki was saved.'
      redirect_to wiki_path(@wiki)
    else
      flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
      render new_wiki_path
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

    if @wiki.save
      flash[:notice] = 'Wiki was saved.'
      redirect_to wiki_path(@wiki)
    else
      flash.now[:alert] = 'There was an error saving the wiki. Please try again.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if !@wiki.private && @wiki.delete
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    elsif @wiki.private && @wiki.delete
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_private_index_path
    else
      flash.now[:alert] = 'There was an error deleting the wiki.'
      render :show
    end
  end

  private

  def wiki_params
    if current_user.admin? || (current_user.premium? && (@wiki.user == current_user))
      params.require(:wiki).permit(:title, :body, :private)
    else
      params.require(:wiki).permit(:title, :body)
    end
  end

  def create_params
    if current_user.admin_premium?
      params.require(:wiki).permit(:title, :body, :private)
    elsif current_user.standard?
      params.require(:wiki).permit(:title, :body)
    end
  end

  def permitted_attributes
    if current_user.admin_premium? && (@wiki.user == current_user)
      [:title, :body, :private]
    else
      [:title, :body]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/charges/new.html.erb
<% if current_user.standard? %><br><br><br><br>
<div class="jumbotron">
  <h2 style="text-align:center">Upgrade To Premium for only $15!</h2><br>
  <p style="text-align:center">As a premium member, you have the ability to manage your own Private Wikis<p>
  <p style="text-align:center">By adding Collaborators, you can create a network of authorized Wiki Contributors for your Wiki!<p><br>
  <div style="padding-left:475px">
    <%= form_tag charges_path do %>
      <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
<% else %>
  You are already Upgraded to Premium!
<% end %>
  <div>
</div>

app/views/collaborators/_form.html.erb
<% collaborators.each do |c| %>
  <tr>
    <th><%= c.name %></th>
    <td><%= c.email %></td>
    <td>
      <% if wiki.collaborators.pluck("user_id").include?(c.id) %>
        <%= link_to 'Remove Collaborator', wiki_collaborator_path(wiki, c.id), method: :delete, class: 'btn btn-danger', id: "collaborators-#{c.id}" %>
      <% else %>
        <%= link_to 'Add Collaborator', wiki_collaborator_path(wiki, c.id), method: :post, class: 'btn btn-success', id: "collaborators-#{c.id}" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/collaborators/index.html.erb
<br><br><br>

<h3>Potential Collaborators For:&nbsp&nbsp&nbsp<small><%=@wiki.title %></small></h3>

<br><br>
<div style=padding-left:45px>
<% @collaborators.each do |c| %>
  <%= c.email %>
  <% if @wiki.collaborators.pluck("user_id").include?(c.id) %>&nbsp&nbsp&nbsp
    <%= link_to " DeleteCollaborator", wiki_collaborator_path(@wiki, c.id), method: :delete, id: "collaborator-#{c.id}", class: 'glyphicon glyphicon-trash', style: "color:red"%></br>
  <% else %>
    &nbsp&nbsp&nbsp<%= link_to " AddCollaborator", wiki_collaborator_path(@wiki, c.id), method: :post, id: "collaborator-#{c.id}", class: 'glyphicon glyphicon-plus',style: "color:green"%></br>
  <% end %>
  <br>
<% end %>
<br>
<%= link_to "Back To Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li style="font-weight:bold"><%= link_to "Home", welcome_index_path %></li>
      <li style="font-weight:bold"><%= link_to "About", welcome_about_path %></li>
      <% if user_signed_in? %>
        <li style="font-weight:bold;float:right"> <%= link_to "#{current_user.email}", edit_user_registration_path %></li>
      <% else %>
        <li style="font-weight:bold"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li style="font-weight:bold"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end%>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
<small>
  <small>
    <div class="row">
    <div style="float:left;padding-top:5px">

    <% if user_signed_in? %>
      <% if current_user.standard? %>
      <div class="btn btn-info btn-xs">
        <span class="glyphicon glyphicon-hand-up">
        <%= link_to "Upgrade to Premium", new_charge_path, class: 'navbar-link', style:"color:white"  %>
      </span>
    </div>
      <% elsif current_user.premium? %>

      <div class="btn btn-info btn-xs">
        <span class="glyphicon glyphicon-hand-down">
        <%= link_to "DowngradeToStandard", edit_user_registration_path, :class => 'navbar-link', style:"color:white"  %>
       </span>
      </div>
      <% end %>

      <div class="btn btn-info btn-xs">
        <span class="glyphicon glyphicon-cog">
        <%= link_to 'AccountSettings', edit_user_registration_path, class: 'navbar-link', style:"color:white" %>
        </span>
      </div>
      <div class="btn btn-info btn-xs">
        <span class="glyphicon glyphicon-log-out">
        <%= link_to "SignOut", destroy_user_session_path, method: :delete, class: 'navbar-link', style:"color:white"  %>
        </span>
      </div>
     <% end %>
    </div>

    <div style="float:right;padding-top:5px">
      <div class="btn btn-warning btn-xs">
        <span class="glyphicon glyphicon-list-alt">
        <%= link_to "PublicWikis",wikis_path, class: 'navbar-link', style:"color:white"  %>
        </span>
      </div>

      <% if current_user != nil && current_user.admin_premium? %>
      <div class="btn btn-warning btn-xs">
        <span class="glyphicon glyphicon-list-alt">
      <%= link_to "PrivateWikis", wikis_private_index_path, :class => 'navbar-link', style:"color:white"  %>
       </span>
      </div>
       <% end %>
    </div>
  </small>
  </small>




  <%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<br><br>
<h1>Blocipedia</h1>
<p>This page is under construction...</p>

app/views/welcome/index.html.erb
<br><br><br><br><br>

<div class="jumbotron">
<h1 style="color:blue">Blocipedia</h1>
<p>Create, read, edit, and collaborate on private and public Wikis!</p>
</div>

<% if !current_user %>
  <%= link_to " Login", new_user_session_path %> or
  <%= link_to " Sign Up", new_user_registration_path %> for an account to interact with Wikis

<% end %>

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
    <h4><%= pluralize(wiki.errors.count, "error") %></h4>
      <% wiki.errors.full_messages.each do |msg| %>
        <p><%= msg %><p>
      <% end %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4"><br>
      <p>Guidelines for Wikis:</p>
      <ul>
        <li>No Naughty Words.</li><br>
        <li>Title Must be 150 Characters or Less</li><br>
        <li>Body Must be 750 Characters or Less</li><br><br>
          <% if @wiki.id? %>
            <% if @wiki.private && (current_user.admin? || (current_user.premium? && (@wiki.user_id == current_user.id)))%><br><br><br><br>
              <%= link_to 'Manage Collaborators', wiki_collaborators_path(@wiki),class: 'btn btn-success btn-xs' %>
            <% end %>
          <% end %>
      </ul>
    </div><br><br>

      <div class="col-md-8">
      <%= form_group_tag(wiki.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
      <% end %>

      <%= form_group_tag(wiki.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
      <% end %>

    <% if current_user.admin? || (current_user.premium? && (wiki.title.nil? || (wiki.user == current_user)))  %>
        <div class="form-group">
          <div style="padding-left:20px">
            <%=f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private Wiki
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success btn-xs' %>
    </div>
  </div>
  <% end %>
</div>

app/views/wikis/_private_wikis.html.erb
<% if current_user.admin_premium? %>
  <h1>My Private Wikis</h1>
  <%= link_to "Create a New Wiki", new_wiki_path, class: 'btn btn-success' %><br><br>

  <% @wikis.each do |wiki| %>
    <% if wiki.private && (current_user.admin? || (current_user.premium? && current_user.wikis.include?(wiki))) %>
    <p><%= link_to wiki.title, wiki %></p>
      <small>Created by <%= wiki.user.name || wiki.user.email%></small>
      </p>
    <%end%>
  <% end %>
<% end %>

app/views/wikis/edit.html.erb
<br><br>
<div class="jumbotron">
  <h1 style="color:blue;float:left;font-family:Copperplate;">Edit Wiki</h1><br><br>
  <p style="float:right; font-size:12px">Wikis are Markdown Enabled! Below is a preview screen to make sure your MarkDown is on Point.<br>
  After you've entered your text, click the toggle button.
  <br> If acceptable, toggle back to black and copy and paste MarkDown text Below!</p>
  </p><br>
  <head>
    <meta charset="utf-8">
    <script src="js/epiceditor.js"></script>
  </head>
  <body>
    <div id="epiceditor"></div>
  </body>
  <script type="text/javascript">
    var editor = new EpicEditor().load();
  </script><br><br>

  <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/index.html.erb
<br><br><br>
<div class="jumbotron">
  <h2 style="float:left">Public Wikis</h2><br><br>
  <% if current_user %>
  <div style="float:right">
    <div class="btn btn-success btn-xs">
      <span class="glyphicon glyphicon-plus">
        <%= link_to "CreateNew", new_wiki_path,style: "color:white; font-weight:bold" %><br>
      </span>
    </div>
  </div>
  <% end %>
</div>

<div style="padding-left:30px">
  <% @wikis.each do |wiki| %>
    <% if !(wiki.private) %>
      <p style=""><%= link_to wiki.title, wiki %>
      <small>Created by <%= wiki.user.name || wiki.user.email%></small>
      </p>
    <% end %>
  <% end %>
</div>

app/views/wikis/new.html.erb
<br><br>
<div class="jumbotron">
  <h1 style="color:blue;float:left;font-family:Copperplate;">New Wiki</h1><br><br>
  <p style="float:right; font-size:12px">Wikis are Markdown Enabled! Below is a preview screen to make sure your MarkDown is on Point.<br>
  After you've entered your text, click the toggle button.
  <br> If acceptable, toggle back to black and copy and paste MarkDown text Below!</p>
  </p><br>
  <head>
    <meta charset="utf-8">
    <script src="js/epiceditor.js"></script>
  </head>
  <body>
    <div id="epiceditor"></div>
  </body>
  <script type="text/javascript">
    var editor = new EpicEditor().load();
  </script><br><br>

  <%= render partial: 'form', locals: {wiki: @wiki} %>
</div>

app/views/wikis/private.html.erb
<% if current_user.admin_premium? %>
  <h1>My Private Wikis</h1><br>
  <%= link_to "Create a New Wiki", new_wiki_path, class: 'btn btn-success' %><br><br>

  <% @wikis.each do |wiki| %>
    <% if wiki.private && (current_user.admin? || (current_user.premium? && current_user.wikis.include?(wiki))) %>
      <p><%= link_to wiki.title, wiki %>
      <small>Created by <%= wiki.user.name || wiki.user.email%></small>
      </p>
    <%end%>
  <% end %>
<% end %>

app/views/wikis/private_index.html.erb
<br><br><br>
<div class="jumbotron">
  <h2 style="float:left">Private Wikis</h2><br><br>
  <% if current_user.admin_premium? %>
  <div style="float:right">
    <div class="btn btn-success btn-xs">
      <span class="glyphicon glyphicon-plus">
        <%= link_to "CreateNew", new_wiki_path,style: "color:white; font-weight:bold" %><br>
      </span>
    </div>
  </div>
  <% end %>
</div>

<div style="padding-left:30px">
  <% if @wikis %>
    <% @wikis.each do |wiki| %>
      <% collab_ids = wiki.collaborators.pluck("user_id") %>
      <p><%= link_to wiki.title, wiki %>
      <small>Created by <%= wiki.user.name || wiki.user.email%></small>
      </p>
    <%end%>
  <% end %>
</div>

app/views/wikis/show.html.erb
<br><br><br>
<div class="jumbotron">
  <div class="media">
    <div class="media-body">
    <h2 class="media-heading"><br>
    <strong><%= markdown(@wiki.title) %></strong><br>
    </h2>
      <div style="row; padding-left:20px">
        <%= markdown(@wiki.body) %><br>
      </div>
      <small>
      <p style="color:gray; font-size:15px">This
      <% if @wiki.private %>
        <span style="color:orange">Private</span>
      <% elsif !@wiki.private %>
        <span style="color:orange">Public</span>
      <% end %>
      Wiki was Submitted<%= time_ago_in_words(@wiki.created_at) %> ago by   <%= @wiki.user.name || @wiki.user.email %>
      </p>
      </small><br>
   </div>
  </div>

  <% if current_user != nil  %>
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success btn-xs' %>
      <% if current_user.admin? || ((current_user.standard? || current_user.premium?) && @wiki.user == current_user) %>
        <%= link_to "Delete Wiki", [@wiki], method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure you want to delete this Wiki?' } %></br>
      <% end %>
  <% end %>
</div>

  <% if @wiki.collaborators.present? %>
    <h3>Collaborators</h3>
    <% @wiki.collaborators.each do |x| %>
      <%= x.user.email %><br>
    <% end %>
  <% end %>
</div>